//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceLib.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeker.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background agents have been disabled by the user. Check Settings in phone..
        /// </summary>
        public static string BackgroundAgentsDisabled {
            get {
                return ResourceManager.GetString("BackgroundAgentsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current week.
        /// </summary>
        public static string CurrentWeekHeader {
            get {
                return ResourceManager.GetString("CurrentWeekHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codermee.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by:.
        /// </summary>
        public static string DeveloperTitle {
            get {
                return ResourceManager.GetString("DeveloperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong combo of year and week.
        /// </summary>
        public static string ErrorMessageWeekConvertion {
            get {
                return ResourceManager.GetString("ErrorMessageWeekConvertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If switched off, the app won&apos;t be able to update the live tile with current week number..
        /// </summary>
        public static string LiveTileUpdatesInfo {
            get {
                return ResourceManager.GetString("LiveTileUpdatesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live tile updates on/off.
        /// </summary>
        public static string LiveTileUpdatesToggleTitle {
            get {
                return ResourceManager.GetString("LiveTileUpdatesToggleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding Weeker.
        /// </summary>
        public static string MailSubject {
            get {
                return ResourceManager.GetString("MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codermee@hotmail.com.
        /// </summary>
        public static string MailTo {
            get {
                return ResourceManager.GetString("MailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date to week.
        /// </summary>
        public static string TransformDateHeader {
            get {
                return ResourceManager.GetString("TransformDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a date.
        /// </summary>
        public static string TransformDateText {
            get {
                return ResourceManager.GetString("TransformDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week to date.
        /// </summary>
        public static string TransformWeekHeader {
            get {
                return ResourceManager.GetString("TransformWeekHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a week.
        /// </summary>
        public static string TransformWeekText {
            get {
                return ResourceManager.GetString("TransformWeekText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.0.0.2.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string VersionTitle {
            get {
                return ResourceManager.GetString("VersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week info.
        /// </summary>
        public static string WeekInfo {
            get {
                return ResourceManager.GetString("WeekInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        public static string WeekText {
            get {
                return ResourceManager.GetString("WeekText", resourceCulture);
            }
        }
    }
}
